export const LIST_PROJECT_ACTION = 'LIST_PROJECT_ACTION'
export const CREATE_PROJECT_ACTION = 'CREATE_PROJECT_ACTION'
export const UPDATE_PROJECT_ACTION = 'UPDATE_PROJECT_ACTION'
export const DELETE_PROJECT_ACTION = 'DELETE_PROJECT_ACTION'

export const LIST_TASK_ACTION = 'LIST_TASK_ACTION'
export const CREATE_TASK_ACTION = 'CREATE_TASK_ACTION'
export const UPDATE_TASK_ACTION = 'UPDATE_TASK_ACTION'
export const DELETE_TASK_ACTION = 'DELETE_TASK_ACTION'