export const LIST_PROJECT_MUTATION = 'LIST_PROJECT_MUTATION'
export const CREATE_PROJECT_MUTATION = 'CREATE_PROJECT_MUTATION'
export const UPDATE_PROJECT_MUTATION = 'UPDATE_PROJECT_MUTATION'
export const DELETE_PROJECT_MUTATION = 'DELETE_PROJECT_MUTATION'

export const LIST_TASK_MUTATION = 'LIST_TASK_MUTATION'
export const CREATE_TASK_MUTATION = 'CREATE_TASK_MUTATION'
export const UPDATE_TASK_MUTATION = 'UPDATE_TASK_MUTATION'
export const DELETE_TASK_MUTATION = 'DELETE_TASK_MUTATION'

export const CREATE_NOTIFY_MUTATION = 'CREATE_NOTIFY_MUTATION'